
name: Build and Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_COMMIT: '058088532e33f23ac1ad31e32ad0bb1ab8e32195'
      VCPKG_DEFAULT_TRIPLET: 'x86-windows'
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg/installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC++ 2015
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Install vcpkg dependencies
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}

    # Avoid error during "vcpkg install" because of long paths.
    - name: Setup short path
      run: |
        subst V: ${{ github.workspace }}

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/vcpkg/installed
          ${{ github.workspace }}/vcpkg/packages
          ${{ github.workspace }}/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ env.VCPKG_COMMIT }}-${{ hashFiles('vcpkg.json') }}

    - name: vcpkg install
      shell: cmd
      env:
        VCPKG_ROOT: V:\vcpkg
        VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      run: |
        cd /d %VCPKG_ROOT%
        .\vcpkg install --triplet=${{ env.VCPKG_DEFAULT_TRIPLET }}

    - name: Package the build
    # -X: exclude extra file attributes
    # -r: recursive
    # -9: maximum compression level
      run: |
        zip -X -r -9 gtk3.24-${{ env.VCPKG_DEFAULT_TRIPLET }}.zip ${{ env.VCPKG_DEFAULT_TRIPLET }} -x  ${{ env.VCPKG_DEFAULT_TRIPLET }}\debug\*

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: gtk3.24-windows
        path: gtk3.24-${{ env.VCPKG_DEFAULT_TRIPLET }}.zip
        if-no-files-found: error

    # Create GitHub Release when a tag is pushed
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: gtk3.24-${{ env.VCPKG_DEFAULT_TRIPLET }}.zip
        generate_release_notes: true