name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:

variables:
 - name : vcpkg.commit
   value: '058088532e33f23ac1ad31e32ad0bb1ab8e32195'
 - name : vcpkg.target.triplet
   value: 'x86-windows'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC++ 2015
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Install vcpkg dependencies
      uses: lukka/run-vcpkg@v11
      inputs:
        vcpkgGitCommitId: $(vcpkg.commit)
      env:
        VCPKG_DEFAULT_TRIPLET: ${{ vars.vcpkg.target.triplet }}
          
    - name: Package the build
      run: |
        zip -X -r gtk3.24-x86-windows.zip x86-windows -x x86-windows\debug\*
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gtk3.24-x86-windows
        path: gtk3.24-x86-windows.zip