name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC++ 2015
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Install vcpkg dependencies
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: D:\a\bleachbit_windows_gtk\bleachbit_windows_gtk/vcpkg
        vcpkgGitURL: https://github.com/microsoft/vcpkg.git
        vcpkgGitCommitId: '058088532e33f23ac1ad31e32ad0bb1ab8e32195'
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/vcpkg.json'
        vcpkgJsonIgnores: 
          - '**/vcpkg/**'
        runVcpkgFormatString: 
          - 'install'
          - '--recurse'
          - '--clean-after-build'
          - '--x-install-root'
          - '$[env.VCPKG_INSTALLED_DIR]'
          - '--triplet'
          - 'x86-windows'
        useShell: true

    - name: Package the build
      run: |
        zip -X -r gtk3.24-x86-windows.zip x86-windows -x x86-windows\debug\*
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gtk3.24-x86-windows
        path: gtk3.24-x86-windows.zip